// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://niezvknirvhmzbeyxbmv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pZXp2a25pcnZobXpiZXl4Ym12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5ODczMDUsImV4cCI6MjA2MDU2MzMwNX0.Y-oOwzpIqJMvvNX1CgbKzXKkIeu9Ex570qiEMMZ2rQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);